- .gitignore
- scripting/shavit-core.sp
> Added pause/resume

- README.md
- scripting/shavit-core.sp
- scripting/shavit-misc.sp
- scripting/shavit-stats.sp
- scripting/shavit-timelimit.sp
- scripting/shavit-wr.sp
Migrate every menu to the new syntax.
> Add table prefix (shavit_core_sqlprefix)

- scripting/shavit-replay.sp
Oh god, if anyone wants to rewrite this code with backwards compatibility it would be cool.
> Fix bots spinning endlessly at the playback's end.

- scripting/include/shavit.inc
- scripting/shavit-core.sp
Code created by https://forums.alliedmods.net/member.php?u=270493 but I'd rather you push it as soon as possible so that I can keep working on the new styles.
- Third Person
- Slowmotion
- Gravity
Should be coming later today/tomorrow.
Thanks
> HSW Additions

- webserver/config.php
- webserver/index.php
- webserver/timer-red.css
- webserver/timer.css
Includes config option to add a new red themes webpanel, including
slight changes to the code to make the default template appear with a
better layout.
> Customized Red Webpanel

- scripting/include/shavit.inc
- scripting/shavit-core.sp
- scripting/shavit-zones.sp
> Add teleport to !end

- scripting/shavit-core.sp
- scripting/shavit-wr.sp
- scripting/shavit-zones.sp
This pull request is because for some reason, my new changes caused shit. Literally broke everything and caused some data loss (new bullshit replay bots :c) and spammed my servers with errors.
> Fix recent MySQL issues

- scripting/shavit-core.sp
- scripting/shavit-wr.sp
- scripting/shavit-zones.sp
i fucked up everything again..
i'll just test everything for some time until i manage to get it working :(
> Revert "Fix recent MySQL issues"

- README.md
- scripting/include/shavit.inc
- scripting/shavit-core.sp
- scripting/shavit-hud.sp
- scripting/shavit-misc.sp
- scripting/shavit-rankings.sp
- scripting/shavit-replay.sp
- scripting/shavit-sounds.sp
- scripting/shavit-stats.sp
- scripting/shavit-timelimit.sp
- scripting/shavit-wr.sp
- scripting/shavit-zones.sp
- smbuild
- webserver/config.php
- webserver/index.php
+ Revamp some of `sm_stats`.
+ Add a whole new fair and competitive ranking system. Use `sm_setpoints <time in seconds> <points>`  to set points for an ideal time (usually \#1 or \#2 in the server).
+ Implement points in WR menus.
+ Implement points in mapsdone (`shavit-stats`).
+ Implement points in web interface.
+ Add some APIs, see `shavit.inc`
To-do before deleting branch:
> Implement rankings

- README.md
- scripting/include/shavit.inc
- scripting/shavit-zones.sp
also tried to make them trigger based but i failed, left the code commented if anyone wants to try
> Add teleport zones

- scripting/shavit-replay.sp
Changed the structure of the way replays are saved, thanks blacky (@chrondog)!
Includes backwards compatibility
> Solve replay saving/loading lag (#193)

- README.md
- scripting/include/bhopstats.inc
- scripting/shavit-hud.sp
Requires [Bunnyhop Statistics](https://forums.alliedmods.net/showthread.php?t=286135) to be installed.
> Rework CS:S key display (#243)

- README.md
- configs/shavit-advertisements.cfg
- scripting/include/SteamWorks.inc
- scripting/shavit-misc.sp
Requires [SteamWorks](https://forums.alliedmods.net/showthread.php?t=229556) for `{serverip}`
> Add more advertisements parameters (#259)

- scripting/include/shavit.inc
- scripting/shavit-zones.sp
**Custom Spawn Location**: #223 
I thought it better to add separate commands for add/removal of spawns as there would probably be more to add/edit if it was through the zones menu. 
I can change it/add it to the zones menu if you would prefer however.
- sm_addspawn    **Adds a custom spawn location**
- sm_delspawn     **Deletes a custom spawn location**
> Custom Spawn

- scripting/shavit-chat.sp
- scripting/shavit-core.sp
- scripting/shavit-hud.sp
- scripting/shavit-misc.sp
- scripting/shavit-rankings.sp
- scripting/shavit-replay.sp
- scripting/shavit-sounds.sp
- scripting/shavit-stats.sp
- scripting/shavit-timelimit.sp
- scripting/shavit-wr.sp
- scripting/shavit-zones.sp
> Remove 'public' where not needed

- README.md
- configs/shavit-styles.cfg
- scripting/shavit-core.sp
- scripting/shavit-hud.sp
- scripting/shavit-misc.sp
- scripting/shavit-zones.sp
> Fix broken advertisements, add shavit_zones_teleporttoend

- scripting/shavit-rankings.sp
It's a tiny but needed change :(
> Tiny change to tier text

- README.md
- scripting/shavit-chat.sp
- scripting/shavit-core.sp
- scripting/shavit-hud.sp
- scripting/shavit-misc.sp
- scripting/shavit-rankings.sp
- scripting/shavit-replay.sp
- scripting/shavit-stats.sp
- scripting/shavit-wr.sp
- scripting/shavit-zones.sp
- translations/shavit-chat.phrases.txt
- translations/shavit-core.phrases.txt
- translations/shavit-hud.phrases.txt
- translations/shavit-misc.phrases.txt
- translations/shavit-rankings.phrases.txt
- translations/shavit-replay.phrases.txt
- translations/shavit-stats.phrases.txt
- translations/shavit-wr.phrases.txt
- translations/shavit-zones.phrases.txt
Things are about to magically appear! >:D
💀  
EDIT: I literally wanna kms right now, I hope you guys are happy.
EDIT: FUCK YOU GABEN.
> Initial Translations Support - Fixes #232

- scripting/shavit-hud.sp
> Alias for sm_hud

- scripting/shavit-core.sp
- scripting/shavit-hud.sp
- translations/shavit-core.phrases.txt
Still needs testing but don't imagine it'll take too long... lol.
> Pause messages - Fixes #296

- gamedata/shavit.games.txt
Source: https://github.com/peace-maker/smrpg/commit/8504b0623afe0b0e5112a2907fa342695f6f84b0
> Update CS:GO Gamedata for speed changes - Fixed #341

- scripting/shavit-zones.sp
- translations/shavit-zones.phrases.txt
Just leave this open for now, will be pushing more :^)
> Translation and misc. fixes to resolve #318

- scripting/shavit-misc.sp
I've seen this suggested in earlier issues and declined as there are other plugins available to do this, however; for the timer to be as all-in-one as possible I think this is definitely a key feature to include.
> Add shavit_misc_removeragdolls

- scripting/shavit-misc.sp
- scripting/shavit-zones.sp
- translations/shavit-misc.phrases.txt
* Optimized and fixed wall snapping's behavior as requested in #375.
* Redid the checkpoints menu, extended the maximum amount of checkpoints to 64 and allowed browsing through them.
> Additions and fixes

- configs/shavit-styles.cfg
- scripting/include/shavit.inc
- scripting/shavit-core.sp
The most popular style on our servers. It's a must have for a true speedrun server experience. It's also the only major style that is missing in your timer. Hope you like it, but if not, then it's ok. :)
You can change the shavit-styles.cfg comment to whatever you think is right.
> Add "Minimum Velocity" or "X VelRun" style

- scripting/shavit-hud.sp
My attempt at making the rainbow HUD _dynamic_.
This approach pretty much uses maximum brightness and saturation values and then loops through every `shavit_hud_gradientstepsize` hue values. Using `shavit_hud_gradientstepsize 1` makes it very slow so personally I feel `15` is a smooth but still noticeable speed.
Initially I did try to use HSV so I could just go through all the hue values in that spectrum but that turned out to be very complicated to convert to HEX or even RGB, this approach has no down sides though as far as I know and is much lighter code-wise.
Also to note, I was initially using a convar to modify a repeating timer to dictate the speed of the gradient but even when using that and the step size the timer speed was just... useless, even using the lowest values it's far …
> Add dynamic HUD gradient (#426)

- README.md
- scripting/shavit-chat.sp
- scripting/shavit-core.sp
CS:S only - the issue doesn't exist in CS:GO!
Also added myinfo for shavit-chat.
> Fixed incompatibilty issue with Chat-Processor.

- scripting/include/shavit.inc
- scripting/shavit-replay.sp
- scripting/shavit-stats.sp
Sorry for caps, it's just **very important**.
> HOTFIX FOR MEMORY LEAKS

- scripting/shavit-misc.sp
This was renamed in the latest csgo update.
> Rename vector name

- configs/shavit-zones.cfg
Small change, but it makes the config much easier to read.
> Make shavit-zones.cfg much easier to read.

- README.md
- addons/sourcemod/configs/shavit-messages.cfg
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-chat.sp
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-stats.sp
- addons/sourcemod/scripting/shavit-timelimit.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-hud.phrases.txt
- addons/sourcemod/translations/shavit-zones.phrases.txt
Tested most (if not all) of the things in-game, so this should be fine :)
* HUD implementation might not be ideal. I might rewrite it if this blows up in the TF2 community somehow and it ends up being problematic.
* TF2 is problematic, so you need Bunnyhop Statistics for the jumps counter to work. Refer to the [installation wiki page](https://github.com/shavitush/bhoptimer/wiki/1.-Installation).
* Follow the TF2 area in [Troubleshooting Issues](https://github.com/shavitush/bhoptimer/wiki/3.-Troubleshooting-Issues) for information.
> Team Fortress 2 support

- addons/sourcemod/scripting/shavit-misc.sp
Wasn't sure about the code-styling on this one. Resolves #554.
> Account for track when respawning on restart (#554)

- addons/sourcemod/scripting/shavit-timelimit.sp
Deleted min value of shavit_timelimit_default. Credits to Nickelony.
> Cleaning up, credits to Nickelony, my first github pullrequest :D

- addons/sourcemod/configs/shavit-styles.cfg
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-rankings.sp
- addons/sourcemod/scripting/shavit-sounds.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-core.phrases.txt
* Added style permissions:
- Added `Shavit_HasStyleAccess` native.
- Added `permissions` setting to styles. Use like "p;style_tas" for example. First section is the flag needed, and the second section is the override for it.
* Micro optimization in spawn point generation.
* Scaled slide zones with speed/gravity. 
* Reworked sounds to emit properly in CS:GO.  Edit: Thanks @strafe for testing!
> New updates

- FEATURES.md
- README.md
- addons/sourcemod/configs/shavit-styles.cfg
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-common.phrases.txt
- addons/sourcemod/translations/shavit-hud.phrases.txt
- addons/sourcemod/translations/shavit-misc.phrases.txt
- addons/sourcemod/translations/shavit-replay.phrases.txt
- addons/sourcemod/translations/shavit-zones.phrases.txt
* Added support for segmented runs. Use `"specialstring" "segments"` to allow a style to use segmented checkpoints.
* This update is very likely to have issues. Needs 'heavy' testing.
* Solves a small part of #158.
Here's a build of 9169629 if you want to help testing: 
[bhoptimer-v2.1.0_9169629.zip](https://github.com/shavitush/bhoptimer/files/1960113/bhoptimer-v2.1.0_9169629.zip)
Will be merged later today if no issues are reported.
> Segmented run support

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-wr.sp
Fixed an exploit to do with checkpoints. Update ASAP to prevent it being abused.
> v2.1.1 hotfix

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-wr.sp
https://github.com/alliedmodders/sourcepawn/pull/319
> Remove semicolon after closing brace on enum structs

- addons/sourcemod/scripting/shavit-wr.sp
its just to fix this little thing :)
> removed ] that was to much

- addons/sourcemod/scripting/shavit-misc.sp
> Don't override teamjoin argument when joining spectator

- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/scripting/shavit-zones.sp
Fix for adminmenu late load or reload
> Fix admin menu

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-replay.sp
Thanks to @shavitush @kidfearless for helping me!!
+ Add a new native **Shavit_GetReplayStatus**
+ Add a new ConVar **shavit_replay_preruntime**
+ Add a new ConVar **shavit_replay_maxlength_instart**
> Implement prerun feature for replay

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-replay.sp
This is a fix made by deadwinter, but he had issues to pull the request somehow.
All the credits for it go to him.
> segmented prespeed fix

- addons/sourcemod/configs/shavit-styles.cfg
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-replay.sp
Implements prerun features thanks @deadw1nter, @Nairdaa 
Add more natives and forwards for checkpoints
Adds jump_multiplier and jump_bonus to style configs
> 2.5.7 pull request

- addons/sourcemod/scripting/shavit-replay.sp
> Prerun should only record when you are in start zone

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-replay.sp
* Remove shavit_hud_prerun_countdown
* Replace ％with %%
> Update FormatSeconds to handle negative time

- addons/sourcemod/scripting/shavit-core.sp
they were only for you to see what I did to test the stuff
> scroll perf ratio fix - removed the debug lines

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-replay.sp
Fully tested, no errors in compiling or in game or on the server. Works with TAS and any other segmented style as well.
Also, removed dynamic time difference. Shit was buggy. Going to be reworked and done way better.
Thanks alot, Deadwinter. Updating on behalf of him.
> Fix hud error bug spam in server console and prespeed on replay

- addons/sourcemod/scripting/shavit-zones.sp
optional cvar to determine wether you want to use player center of mass/player hitbox for touching zones
> Add hitbox/center mass cvar

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/translations/shavit-core.phrases.txt
Also doesn't calculate offsets when NoZAxisSpeed is set to 0 and player is jumping from within the startzone, as requested by rumour.
> Fix offsets, add offset natives for styles like TAS

- addons/sourcemod/scripting/shavit-misc.sp
deadwinter says the blame is 33% him, 33% me and 34% shavit cus it's his timer
> cp bug fix

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-zones.sp
> Fix offset bug and add GetStageZone native

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-rankings.sp
- addons/sourcemod/scripting/shavit-wr.sp
Made `!wr %s` & `!tier %s` with a non-existent map print `Map %s was not found` from #770
Also deduplicated some functions.
> Wr suggestions

- addons/sourcemod/scripting/shavit-hud.sp
> add turn binds to !keys

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/translations/shavit-hud.phrases.txt
- Fixed deleting wrong replay files while using wipeplayer ( #927 )
- Added an option to show rank on Topleft hud ( #949 )
> Yes very good

- addons/sourcemod/scripting/shavit-hud.sp
Before it was hardcoded to cut up to 14 bytes on CSGO and was 128 bytes on all other games, this pr adds ``shavit_hud_specnamesymbollength`` where you can control how much symbols you want to display per client in spec panel, this change respects multibyte characters and they are counted as one symbol.
As an example here are some screenshots:
``shavit_hud_specnamesymbollength 32``
``shavit_hud_specnamesymbollength 6``
> Spectator panel player name truncation improvement

- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/translations/shavit-misc.phrases.txt
The player's timer is stopped before teleporting the client too so dw about anything
> Allow !goto/!tpto from start/end zone

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/translations/shavit-core.phrases.txt
this was done because someone paused in the tunnel on badges, went into spec, and came back in the void causing them to not be able to resume
unsure if this could be abused (any more than !pause could be already)
perhaps pausing as you slide off a platform, into a trigger, resuming and then getting a boost?
are any maps like that?
> allow !resume when not on the ground

- addons/sourcemod/scripting/shavit-misc.sp
Fixes currently big memory leak related to segmented cps.
> Delete frames from cpcache on entry deletion

- addons/sourcemod/scripting/shavit-hud.sp
> useless pr, but KiD asked for it

- addons/sourcemod/scripting/shavit-core.sp
~~Force block `S`~~ #944
Block SHSW on HSW while still allowing S to be used in the air
> block s on regular hsw (so you can't shsw...)

- addons/sourcemod/scripting/shavit-chat.sp
Also untested so far, but still probably fine...
> remove diy GetRandomInt

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-misc.sp
Untested so far but probably fine, right? Intended to be used by another plugin but maybe the teleport count could be added to the db eventually?
> add Shavit_GetTimesTeleported()

- addons/sourcemod/scripting/shavit-stats.sp
Fixed query errors on mysql v8. (profile display and per style map statistics)
> Improved mysql v8 support

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-wr.sp
some niche api that i'll be using in another plugin
will probably merge in a few hours since it works fine rn unless someone else wants some changes to this
> add timestamp to finish-forwards. add Shavit_ShouldSaveReplayCopy and Shavit_OnReplaySaved

- addons/sourcemod/scripting/shavit-misc.sp
A bit annoying to always have this restart warning when segging long maps and trying to go to noclip etc.
> Remove restart warning for a segmented style

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-zones.phrases.txt
Please suggest anything you want modified and I'll try my best to get to it as soon as possible.
> Implemented SetStart/DeleteSetStart

- addons/sourcemod/translations/shavit-core.phrases.txt
Minor change to the core phrases translation file.
> Update core phrases

- addons/sourcemod/scripting/shavit-misc.sp
just an 1-line fix.
preview: https://streamable.com/kilkhh
edited title cuz nairdaaaaaaaaaa said it
> Fix player world damage with shavit_misc_godmode 1

- addons/sourcemod/scripting/shavit-core.sp
from the range as it can be mistaken with lower case L
> remove capital i

- addons/sourcemod/scripting/shavit-replay.sp
there is only one and correct number to be used as default
> fix the default number

- addons/sourcemod/scripting/shavit-misc.sp
because @GAMMACASE is too lazy to pr
> add playerchatwheel to radiocommands

- addons/sourcemod/translations/shavit-misc.phrases.txt
> such grammar much wow

- addons/sourcemod/scripting/shavit-stats.sp
- addons/sourcemod/translations/shavit-stats.phrases.txt
Shoutout to Nairdaa for the idea & testing, GAMMACASE, rumour, carnifex for the feedback
**\*Massive query alert\***
[The menu preview](https://media.discordapp.net/attachments/852705529745768488/887738785629093898/unknown.png)
> Rework stats menu

- addons/sourcemod/scripting/shavit-mapchooser.sp
> Add timeleft to HideRTVChat

- .github/FUNDING.yml
i don't work on this anymore so yea..
> removed sponsor links

- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/translations/shavit-wr.phrases.txt
Only tested with the client itself, specifying a player should also work theoretically
What it looks like right now ![preview](https://i.imgur.com/LIN0A1W.png)
> Implementation of !pb / !time (#636)

- addons/sourcemod/scripting/shavit-stats.sp
fix exploit allowing to "farm" playtime while spectating
> stats exploit fix for playtime per style

- addons/sourcemod/scripting/shavit-replay-playback.sp
- addons/sourcemod/scripting/shavit-replay-recorder.sp
https://discord.com/channels/389675819959844865/934225273866563605/953935648065191976
these implementations should not be done before the style configs loaded
this fix is for those who install bhoptimer at the first time
> fix creating replay-directories issue

- addons/sourcemod/scripting/shavit-mapchooser.sp
> add two additional commands for nomlist

- addons/sourcemod/scripting/include/shavit/hud.inc
- addons/sourcemod/scripting/shavit-hud.sp
GitHub is showing this weirdly but the main section of code was just changed to have a guarding if statement and then tabbed back, code for the forwards similar to top left
> add keyhint forwards and forceUpdate

- addons/sourcemod/scripting/shavit-core.sp
> add backwards check for sync

- addons/sourcemod/scripting/shavit-checkpoints.sp
> Use "KiD Fearless" instead of "kidfearless" in shavit-checkpoints author list

- addons/sourcemod/scripting/shavit-zones.sp
This adds more recent zone types to the hookzone menu.
> Add new zone types to hookzone menu

- .github/workflows/ci.yml
- README.md
- addons/sourcemod/scripting/include/shavit/replay-file.inc
- addons/sourcemod/scripting/include/shavit/replay-recorder.inc
- addons/sourcemod/scripting/include/srcwr/floppy.inc
- addons/sourcemod/scripting/shavit-replay-recorder.sp
~~Prone to explosions probably.~~ Perfectly non-explodable.
Grab extension bins at https://github.com/srcwr/srcwrfloppy/releases
TODO:
- ~~better error logging & handling in the extension~~
- ~~add link in bhoptimer README~~
- test more
> Use an extension to save replays asynchronously

- addons/sourcemod/scripting/shavit-replay-playback.sp
L 07/18/2025 - 06:35:33: [SM] Exception reported: Array index out-of-bounds (index -1, limit 256)
L 07/18/2025 - 06:35:33: [SM] Blaming: shavit/shavit-replay-playback.smx
L 07/18/2025 - 06:35:33: [SM] Call stack trace:
L 07/18/2025 - 06:35:33: [SM]   [1] Line 3015, shavit-replay-playback.sp::DeleteConfirmation_Callback
> shavit-replay-playback.sp - fix error in case where style == -1
