shavitush/bhoptimer

- scripting/shavit-hud.sp
L 10/15/2015 - 13:39:16: [SM] Native "ConVar.SetBool" reported: Invalid convar handle 0 (error 4)
L 10/15/2015 - 13:39:16: [SM] Displaying call stack trace for plugin "shavit-hud.smx":
L 10/15/2015 - 13:39:16: [SM]   [0]  Line 103, shavit-hud.sp::OnConfigsExecuted()
> hud module causes error on cs:s

- scripting/shavit-core.sp
It's better if the player can use all keys on ground if he selects a style like w-only. Makes walking on ground easier!
Also it would be better to block prejump on start zone because every prejump is different and the player doesn't start with the same speed every time. With this fix, times can be compared much better. :) You could also do a cvar for this.
> Allow keys on ground & block prejump in start zone

- scripting/shavit-misc.sp
This is significant:
If player uses noclip and flies 45 - 90 degrees up in the air in the start zone and disables noclip before he leaves the start zone, he can start the timer and fly/shortcut right into another stage or even to the end zone. (Bug found randomly by CRNO)
This line of code fixes it and is working fine on my server :)
Could be also fixed differently e.g: Setting the Y-speed of the player to 0 when he disables noclip in the start zone :+1:
> Fix Noclip Abuse

- README.md
- configs/shavit-chat.cfg
- scripting/include/dhooks.inc
- scripting/include/dynamic.inc
- scripting/include/rtler.inc
- scripting/include/shavit.inc
- scripting/shavit-chat.sp
- scripting/shavit-core.sp
- scripting/shavit-misc.sp
- scripting/shavit-rankings.sp
- scripting/shavit-replay.sp
- scripting/shavit-stats.sp
- scripting/shavit-timelimit.sp
- scripting/shavit-wr.sp
- scripting/shavit-zones.sp
- smbuild
Chat **(NEW!)**
--
Requires [Dynamic](https://forums.alliedmods.net/showthread.php?t=270519) to compile and run.
> Implement chat handler

- scripting/shavit-core.sp
- scripting/shavit-hud.sp
- scripting/shavit-misc.sp
- scripting/shavit-replay.sp
- translations/shavit-misc.phrases.txt
1. Added a checkpoints menu, including `sm_save` and `sm_tele`. Use `sm_cp` or `sm_cpmenu` to open the menu! See #313.
2. Optimized per-player `sv_airaccelerate` so the server won't make two SourceMod calls but only one. An even better micro-optimization would be to cache the player's status (alive/dead) instead so there's only one call to SourceMod (`SetConVarInt`), and only when it's needed as PreThink gets called A LOT.
3. I'm not sure what went wrong, but I tested the timer in my local server and one replay bot would stay in the spectator team so I added `shavit_replay_defaultteam`. Values are 2 for T and 3 for CT.
I'm also a bit confused about why my branches duplicate some commits.. does anyone know what could be wrong?
> Additions and optimizations

- scripting/shavit-hud.sp
This was mentioned in #318, whether the timer is running or paused the player's best will be indented 1 tab too far, this seems to happen no matter the player's current running time/position.
> Fix CS:GO HUD indentation

- configs/shavit-zones.cfg
- scripting/include/shavit.inc
- scripting/shavit-core.sp
- scripting/shavit-hud.sp
- scripting/shavit-misc.sp
- scripting/shavit-zones.sp
- translations/shavit-zones.phrases.txt
- Fixes #161.
I have restructured the whole zones plugin which will result in MASSIVE optimizations and ease of use, including:
* Tracks are now a thing. There isn't any implementation for them in other modules yet, but the backend is mostly ready.
* The whole code is much much better. It's easier to read, to understand and to work with.
* 3D boxes will not be generated often at all, but instead only once (when the zones are loaded from the database).
* The hard limit for zones right now is 64, but shouldn't be an issue to increase. AFAIK Source limits entities to a certain amount, and now zones are based on `trigger_multiple` so it's a failsafe. The value can be safely increased from within `shavit.inc` for CS:GO as the hard cap for entities is 4096 there.
* Zones use `trigger_multiple`s …
> Zones plugin rewrite

- configs/shavit-styles.cfg
- scripting/include/shavit.inc
- scripting/shavit-chat.sp
- scripting/shavit-core.sp
- scripting/shavit-hud.sp
- scripting/shavit-misc.sp
- scripting/shavit-replay.sp
- scripting/shavit-wr.sp
- scripting/shavit-zones.sp
- translations/shavit-wr.phrases.txt
- translations/shavit-zones.phrases.txt
* Added the ability to create zones by aiming for convenience.
* Added return values for timer start/end, example:
```sp
#include <sourcemod>
#include <shavit>
public Action Shavit_OnStart(int client)
{
char[] name = new char[MAX_NAME_LENGTH];
GetClientName(client, name, MAX_NAME_LENGTH);
// fuck you woe
if(StrEqual(client, "woe"))
{
return Plugin_Stop;
}
return Plugin_Continue;
}
public Action Shavit_OnFinishPre(int client, any snapshot[TIMERSNAPSHOT_SIZE])
{
snapshot[bsStyle] = view_as<BhopStyle>(1);
snapshot[iJumps] = 1;
return Plugin_Changed;
}
```
Documentation:
```sp
/**
* Called when a player's timer starts.
* (WARNING: Will be called every tick when the player stands at the start zone!)
*
* @param client					Client index.
* @return							Plugin_Continue to do nothing or anything …
```
> More additions

- FEATURES.md
- configs/shavit-advertisements.cfg
- configs/shavit-chat.cfg
- configs/shavit-readme.txt
- configs/shavit-replay.cfg
- configs/shavit-sounds.cfg
- configs/shavit-styles.cfg
- scripting/include/shavit.inc
- scripting/shavit-core.sp
- scripting/shavit-hud.sp
- scripting/shavit-misc.sp
- scripting/shavit-rankings.sp
- scripting/shavit-replay.sp
- scripting/shavit-sounds.sp
- scripting/shavit-stats.sp
- scripting/shavit-wr.sp
- scripting/shavit-zones.sp
- translations/shavit-core.phrases.txt
- translations/shavit-hud.phrases.txt
- translations/shavit-misc.phrases.txt
- translations/shavit-replay.phrases.txt
- translations/shavit-wr.phrases.txt
- translations/shavit-zones.phrases.txt
I'm trying to speed up development, as you can see :)
* Added zone edit capabilities. (As requested in #299)
* Made zone deletion menu mark zones if you're inside them.
* Added sounds for `worst` record and added `Shavit_OnWorstRecord`, as requested in #293. Also re-implemented `Shavit_GetRecordAmount` because the implementation disappeared for some reason..
* Added 'smart' map lookup for `sm_wr` (per #268). You can now write `sm_map dges2` for a lazy lookup of `bhop_badges2`, or `sm_wr yonk` for a lookup of `kz_bhop_yonkoma` etc. For the yonkoma example, the first map (sorted by alphabet ascendance) will be chosen.  So `bhop_kz_yonkoma_ez` will be the first result if it's present in the server.
* Implemented `shavit_misc_dropall` to allow every weapon to be dropped (including …
> Additions (!replay, SurfHSW and more)

- scripting/shavit-core.sp
- translations/shavit-core.phrases.txt
This isn't really needed anymore since a player's current style appears in their HUD and is greyed out in the menu. I've also changed the layout a little simply so it matches the !wr menu appearance.
> Remove current style text from style menu

- configs/shavit-styles.cfg
- scripting/include/shavit.inc
- scripting/shavit-core.sp
I've discovered this yesterday by accident, so I tested it a little and tbh, IT'S AMAZING! You can set it to 20 and have a slightly higher gain per jump which feels very natural. You can also set it to 200 for something more challenging. Hope you like it! :)
Edit: Just fixed the order in shavit-core. Everything should be fine now.
Let me know if I should update shavit-styles.cfg to the newest version aswell.
> Add "bonus_velocity" to the style settings

- scripting/shavit-misc.sp
Hides all the blood effects including decals, splashes and other particles. Especially useful on hard maps where everyone is sitting at the spawn, hitting each other just to make the map "slightly" more red. :>
Not to mention that blood decals can sometimes make maps slightly harder if you have a lot of them in one place.
> Add "shavit_misc_noblood" for hiding blood effects.

- scripting/shavit-timelimit.sp
- translations/shavit-common.phrases.txt
I've slightly redesigned the shavit-timelimit plugin because it wasn't very useful. Now it's something you SHOULD have on your server.
**New Features:**
+ "Timelimit Config" - enables the following game settings:
"mp_do_warmup_period" "0"
"mp_freezetime" "0"
"mp_ignore_round_win_conditions" "1"
+ "ForceMapEnd" - forces the map to end after the timelimit (with translations support!).
+ More CVars.
**New CVars:**
+ "shavit_timelimit-config" - enables "Timelimit Config".
+ "shavit_timelimit_dynamic" - enables the dynamic timelimit.
+ "shavit_timelimit_forcemapend" - enables "ForceMapEnd".
_I've remade this PR so it looks much cleaner and instead of having 12 useless commits, there's just gonna be 1 big commit._
> Redesign of shavit-timelimit.

- scripting/shavit-misc.sp
example: make a checkpoint then hold +duck and try to teleport to it with !tele or sm_tele and it'll say that you must be ducking to teleport and it also says you teleported while you were not teleported
> fix it saying you teleported when you might've not

- addons/sourcemod/configs/shavit-zones.cfg
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-chat.sp
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-rankings.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-timelimit.sp
- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-misc.phrases.txt
New natives! As requested in #504
```sp
/**
* Gets the map tier for a specified map.
* Use the map's display name.
*
* @param map						Map to get the tier of.
* @return							Map tier. 0 if no results were found.
*/
native int Shavit_GetMapTier(const char[] map);
/**
* Gets a StringMap that contains all the cached map tiers.
*
* @return							StringMap with {const char: map, int: tier} structure.
*/
native StringMap Shavit_GetMapTiers();
```
Usage example:
```sp
#include <sourcemod>
#include <shavit>
public void OnPluginStart()
{
RegConsoleCmd("sm_xd", xd);
}
public Action xd(int client, int args)
{
char map[] = "de_nuke";
int tier = Shavit_GetMapTier(map);
ReplyToCommand(client, "[1] %s: %d", map, tier);
StringMap maps = Shavit_GetMapTiers();
if(maps.GetValue(map, tier))
{ …
```
> Additions and fixes

- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-zones.sp
* Fixes exploit with buttons in KZ maps.
* Fixes setups similar to [badges' "unbreakable boosts"](https://gamebanana.com/prefabs/4934) breaking in CS:GO. [@GeorgeRiley's prefab](https://gamebanana.com/prefabs/6677) should be unaffected by this glitch. This glitch also affected just about every booster in Serz's maps, including _bhop_cutekittenz_, _bhop_idiosyncrasy_ and _bhop_flocci_.
> Critical update

- .travis.yml
- README.md
- addons/sourcemod/configs/shavit-replay.cfg
- addons/sourcemod/configs/shavit-styles.cfg
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-chat.sp
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-rankings.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-stats.sp
- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-core.phrases.txt
* Made it so that you can configure the replay data folder; fixes #570.
* Fixed a formatting issue with the top-left HUD. Players could previously cause formatting issues with control characters there.
* Fixed an issue where the total records count on other maps' WR menu is incorrect.
* Made the grid visualization less opaque than before.
* Added an extra native for the replay's API: `Shavit_GetReplayBotType`, also added the `ReplayBotType` type.
* Changed !spec to automatically forward you to the replay bot as long as arguments aren't supplied; fixes #574.
* Added `float oldtime` as a parameter to the `Shavit_OnFinish` forward.
* Reworked checkpoints. Now they're not actually 'capped' but rather soft-capped at 1,000 to avoid filling up the whole heap. You can change this manually by …
> Some updates after a while with none

- FEATURES.md
- addons/sourcemod/configs/shavit-chat.cfg
- addons/sourcemod/scripting/include/chat-processor.inc
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-chat.sp
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-rankings.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-chat.phrases.txt
Chat ranks have finally arrived. It's pretty self explanatory.
Check `addons/sourcemod/configs/shavit-chat.cfg` and update your translation files for this to work.
Other stuff:
* Fixed restart not resetting your pause status.
* Fixed replay abortion after the playback is over. It used to replay the same demo over and over.
* Added setting 4 to `shavit_misc_prespeed`. It allows prespeeding but only up to the value of `shavit_misc_prestrafelimit`.
* Fixed checkpoint saving when not spectating a valid player.
* Added the ability to save checkpoints from the replay bot.
* Removed trigger hooking from replay bots. This will only be annoying in *very specific maps*. SAME, SAME, INU INU INU (you can remove triggers like yonkoma's with [Stripper:Source](https://forums.alliedmods.net/showthread.php …
> Chat ranks!

- .gitignore
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-chat.sp
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-misc.phrases.txt
* Addressed CP menu bugs.
* Addressed an issue where donor plugins not always allowing players to use custom titles.
* Addressed an issue that caused chat titles to not always show.
* Fixed CS:S HUD not showing track properly.
* Fixed pre-zoned maps not saving spawn points if you just started the server.
* Removed duck/unduck requirement for checkpoints. Upon teleporting, the plugin will automatically adjust you to the state of the checkpoint.
* Fixed the 'to X rank' parameter when using percentile ranking in titles.
* Reworked gun shot muting. Now it supports TF2, and I've fixed the issue that caused others' gun shots to not play at all in CS:GO.
* Added `shavit_core_defaultstyle`. Usage: style ID. Add an exclamation mark as the prefix to ignore style cookies (i.e. "!3" to force everyone …
> Begone bugs! (v2.0.2)

- addons/sourcemod/configs/shavit-replay.cfg
- addons/sourcemod/scripting/shavit-replay.sp
Currently the `{styletag}` variable in `shavit-replay.cfg` doesn't work as the style string is never copied to the buffer. This also makes the documentation a little clearer as the styles key is `clantag` not `styletag`.
> Copy missing style string in shavit-replay + docs

- README.md
The link for the installation wiki page was pointing to a dead link (what I assume was the old title of the page). It now points to the wiki again. I haven't gotten a chance to play much for a while but I still love what you're doing even if I can't experience it. I'm happy to help any way I can.
> Fixed a dead link

- addons/sourcemod/configs/shavit-chat.cfg
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-chat.sp
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/translations/shavit-chat.phrases.txt
- addons/sourcemod/translations/shavit-misc.phrases.txt
* Fixed errors.
* Reworked checkpoints to not be so poopoo.
* Fixed memory leak with checkpoints.
* Fixed low gravity styles being trash with boosters.
* Fixed HUD showing wrong speeds for slower/faster styles.
* Fixed shavit_misc_prespeed 4. Set to 4 and combine with shavit_core_nozaxisspeed 1 to get the same behavior that SourceCode timer has.
* Added shavit_replay_botweapon. Choose whatever weapon you want the bots to have.
* Added shavit_replay_botplususe. You can disable bots from using +use.
* Added !ranks command in chat module. This shows a list with all* the visible chat titles. Select an entry in the menu to preview the chat rank!
* Easter eggs and privileged titles are excluded from this menu.
* Added `"easteregg"` and `"flag"` settings to chat titles. The former decides on if …
> very good, yes... (2.3.0)

- addons/sourcemod/scripting/shavit-hud.sp
Before that fix raw data printed in hud was:
```
<pre><span class='fontSize-l'>
<span color='#FF0000'>2:48.2</span>
<span color='#A0FFFF'>0 u/s</span>
10 Jumps
34 Strafes (84.5)
<span color='#797FD4'>Normal</span></span></pre>
```
which left 1st line separate from others, which results in empty line.
That pr fixes it, and so raw data now will look like that:
```
<pre><span class='fontSize-l'><span color='#00FF00'>0.0</span>
<span color='#A0FFFF'>0 u/s</span>
0 Jumps
0 Strafes (0.0)
<span color='#797FD4'>Normal</span></span></pre>
```
which removes empty line.
> Fixed empty line at the beginning for csgo hud.

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
This adds 3 new forwards that will let people modify the topleft hud and clantags for individual clients.
> Add forwards for topleft hud and clantag changes

- addons/sourcemod/scripting/shavit-hud.sp
This replaces the tier text in non-main start zones with the track name, as well as indenting the first line to center it.
Preview:
Closes #748
> Start zone HUD adjustments

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-replay.sp
Adds 2 new natives. Shavit_GetClientFrameCount to retrieve the number of frames a client has in their run. and Shavit_GetReplayFrames to retrieve a copy of the replay bot data for the given style and track.
> Added "Shavit_GetClientFrameCount" and "Shavit_GetReplayFrames"

- addons/sourcemod/scripting/shavit-core.sp
This new line will fix the native Shavit_SetClientTimescale by not
resetting the timescale of the player to the style default after each
jump
> Fix timescale being reset to styles default (fix #892)

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/translations/shavit-hud.phrases.txt
Thanks Kamay & ici & Promises & Nairda for help.
- Fix an issue that prerun frame size is bigger than intended size when ``shavit_replay_prerun_always`` is 0
- Add dynamic time difference (#818)
> Remove extra prerun frame, Add dynamic time difference

- addons/sourcemod/gamedata/shavit.games.txt
- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-core.phrases.txt
- addons/sourcemod/translations/shavit-hud.phrases.txt
Two new cvars:
- shavit_core_useoffsets (0/1) 
- shavit_core_debugoffsets (1/0)
Tick calculation is now done in IGameMovement::ProcessMovement
Added tick fractioning system from Momentum Mod.
Added StartReplay native to allow support for per-player replays. 
Tested and working on both csgo and css.
> New timer method, tick fractions & StartReplay native

- addons/sourcemod/scripting/shavit-misc.sp
The convar says `-1 - Until map change` which doesn't work. Persistent data is deleted by the timer every 10 seconds due to `fTime - aData.fDisconnectTime >= gCV_PersistData.FloatValue` always being true when shavit_misc_persistdata is -1
> fix using -1 for shavit_misc_persistdata

- addons/sourcemod/scripting/shavit-misc.sp
An `index` of 0 becomes -1 here
https://github.com/shavitush/bhoptimer/blob/05614c1d514c053bf062bfb4cd1e7f997512c3e3/addons/sourcemod/scripting/shavit-misc.sp#L2413
```
L 10/15/2020 - 02:36:14: [SM] Exception reported: Invalid index -1 (count: 0)
L 10/15/2020 - 02:36:14: [SM] Blaming: shavit-misc.smx
L 10/15/2020 - 02:36:14: [SM] Call stack trace:
L 10/15/2020 - 02:36:14: [SM]   [0] ArrayList.GetArray
L 10/15/2020 - 02:36:14: [SM]   [1] Line 2409, shavit-misc.sp::TeleportToCheckpoint
L 10/15/2020 - 02:36:14: [SM]   [2] Line 1779, shavit-misc.sp::Command_Tele
```
(line numbers aren't the same due to other changes)
> fix error that happens if you 'sm_tele 0' with no checkpoints

- addons/sourcemod/scripting/shavit-misc.sp
With the radar disabled, it'll come back after an hour or if you lag.
You can replicate this by... waiting an hour, or with
```
sm_rcon sv_cheats 1
net_droppackets 200
```
The `GetURandomFloat()` call is used because the radar won't go away if you set the m_flFlashDuration to the same thing over and over.
> [CSS] continuously set m_flFlashDuration so the radar goes away

- addons/sourcemod/scripting/shavit-replay.sp
This is a part of the fix for #953
> grab Z from replay origin for dynamic time diff

- addons/sourcemod/scripting/shavit-replay.sp
https://github.com/shavitush/bhoptimer/issues/953#issuecomment-674516766
"Also, when you go back to startzone (not with !r) your dynamic time is not back to 0 when you have more than 10 seconds on the timer (you can have even 30 on it, walk back to startzone, walk out and it will show -10 sec on dynamic timer right away)."
Someone else test this patch too @Nairdaa
> Don't include preframe count for dynamic time diff

- addons/sourcemod/scripting/shavit-chat.sp
"this breaks the parsing and it always parses CS:S section"
made a PR on behalf of GAMMACASE
also by the way removed the useless " \t \n \r " cus it's already in there defined as hex, pointless to have it defined twice
> minor shavit-chatsettings fix

- addons/sourcemod/scripting/shavit-chat.sp
Actual fix for the shavit-chatsettings.cfg, also fixed back what was incorrectly removed before.
> Fixed incorrect kv traversal for shavit-chatsettings.cfg

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-rankings.sp
- addons/sourcemod/scripting/shavit-replay.sp
- addons/sourcemod/scripting/shavit-stats.sp
- addons/sourcemod/scripting/shavit-wr.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-common.phrases.txt
i want feature parity with surf timers like ksf's so i did this
up to 8 bonuses should work now since I expanded the TRACKS_SIZE (i have no idea what the max number of bonuses a map has so I just made it 8)
_also i'm very lazy, carnifex_
todo:
- a menu added for !bwr that allows you to select which bonus number to view times from
- ~~add the number to BWR text [hereish](https://github.com/shavitush/bhoptimer/pull/982/files#diff-a6d6c2b4761eea8f68202daa7a99cb0b1fcd07186b000ca75e9db88a587769c5R1151)~~ nevermind. not needed
- ~~fix slow zone loading on map change... went from 7~ seconds to 30~ seconds on my server...~~ fixed
- caused by recalcing a shit ton of zones/styles on map start [here](https://github.com/shavitush/bhoptimer/blob/ac889722d5a648c586ebc6c0476a11347b21eb53/addons/sourcemod …
> Multiple bonuses

- addons/sourcemod/scripting/shavit-replay.sp
If any plugin changes the tickrate of the server (i.e Tickrate Control by Rostu), the playback of the replay's timer might be at the wrong speed. To fix this we just make sure gF_Tickrate is up to date when starting the replay.
> Fixed bad replay timer playback.

- addons/sourcemod/scripting/shavit-zones.sp
Some maps have translucent walls and floors and cursor just wont snap on it and instead snaps to whatever is kilometer behind the translucent wall/floor, which makes it just annoying. This changes TraceRay masks to use MASK_PLAYERSOLID that respects texture translucency and fixes described problem.
> Change TraceRay masks to MASK_PLAYERSOLID

- addons/sourcemod/scripting/shavit-misc.sp
This fixes incorrect memory allocation that allows users to go beyond the ``shavit_misc_maxcp_seg`` limit and spam segmented checkpoints to cause server to crash due to memory limit.
> Fix incorrect memory allocation for segmented checkpoints

- addons/sourcemod/scripting/shavit-chat.sp
If the shavit-rankings plugin isn't loaded, the calls to its natives will cause an exception and the client's messages will not be formatted correctly.
> Fix unchecked dependency on shavit-rankings in shavit-chat

- addons/sourcemod/gamedata/shavit.games.txt
- addons/sourcemod/scripting/shavit-replay.sp
Replays bots have been missing the jumping animation for too long.
How it looks in csgo:
https://streamable.com/erfvay
How it looks in css:
https://streamable.com/mimwhf
> Force replay bot jump animation

- addons/sourcemod/scripting/shavit-zones.sp
to prevent fails for people that are using a prefix 
[shavit-zones.smx] Timer (zones GetStageZone) SQL query failed. Reason: Table 'bhoptimer.mapzones' doesn't exist
Query callback. Number of returned results: 399, Maps added to g_aMapList:284, g_aAllMapsList.Length:287, g_mMapList:286
> added missing prefix

- addons/sourcemod/scripting/shavit-hud.sp
The buffer size of 128 is quite small, as in worst case scenario player name length might be exactly 128 bytes, so it'll clearly won't fit 3 of them + some other text, increasing it to something like 512 bytes should be sufficient. Also here's the real example of the problem:
> Increase top left WR hud buffer size

- addons/sourcemod/scripting/shavit-chat.sp
Currently it is possible to hit an infinite loop if the sm_ccname has non correct length sequence at the end (eg. ``^FFF``, where it would expect ``^FFFFFF``), this pr adds the necessary checks to verify that end of the string was set correctly.
Also ``when u pr make sure to notice "nairda found a new feature in the timer to crash any server with cc access"`` (c) Nairda.
> Fix infinite loop in RemoveFromString()

- addons/sourcemod/scripting/shavit-replay.sp
Because old replay formats don't have style and track ID in the header, the ID will default to 0. This causes issues such as replays of style ID > 0 showing the replay name as the player with the record for style with ID 0.
> Pass style and track ID to replay header reader for use with older replay formats

- addons/sourcemod/scripting/shavit-misc.sp
Having this check allows players to abuse the practice mode, to clear their targetname/classname on map start and abuse the map to do skips etc. (This is also what the comment was suggesting there I assume). Unsure why the check was there in the first place, but tested this for like a few month I believe and everything seems to be fine (on 2.6.0 version tho, but also tested locally on latest version too).
> Remove practice mode check for target/classname reset

- addons/sourcemod/scripting/include/shavit.inc
- addons/sourcemod/scripting/shavit-hud.sp
- addons/sourcemod/scripting/shavit-wr.sp
Currently there's a problem with multi byte characters being cut early in the !recent menu:
Here's after this pr:
This pr should handle all multi byte symbols correctly, also there's already a TrimPlayerName() implementation in shavit-hud, and I'm unsure if it's better to just move it to shavit.inc as a stock and use from there as it might come handy again somewhere else idk.
> Handle multi byte symbols in player names in !recent menu correctly

- addons/sourcemod/configs/shavit-mapfixes.cfg
- addons/sourcemod/gamedata/shavit.games.txt
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-zones.sp
This change sets ``shavit_misc_resettargetname`` to 0 being default. Also does changes how events are handled when player is teleported from outside the start zone. This implementation accounts for the OnStartTouch events that might be in the start zone triggers and wont clear these events out.
Main logic behind the implementation is that events are applied at the same tick after teleport from both the trigger that was teleported from (OnEndTouch) and to the destination trigger (OnStartTouch), but they are applied too late for the Shavit_OnStartPre() forward to catch them, thus to clearly erase all events from the OnEndTouch DoPhysicsUntouch() called (forcing events to be applied) and events are cleared right after (This is done for 2 ticks after the teleport was done outside the start …
> Change the behaviour of shavit_misc_resettargetname

- addons/sourcemod/configs/shavit-mapfixes.cfg
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-zones.sp
This pr prevents issues that were talked about in https://github.com/shavitush/bhoptimer/pull/1134 pr, basically teleporting mid way bhop triggers or any other same trigger setups might cause issues and lock wrong targetname on the player (For example 2 events fired with delay 0.9 and 1.0 where 1st one sets your targetname to ``bhop`` for example and other one clears it out, teleporting to start zone in between 0.9 and 1.0 would lock your targetname to being ``bhop`` as the still ongoing event with 1.0 delay would be erased). This pr solves this issue by manually resetting targetname and classname in situations when player is teleported to start zone, or when Shavit_OnRestart() is called (only when no start position is used) and all that is done before any events from start triggers are …
> Fix targetname and classname locking

- addons/sourcemod/scripting/shavit-misc.sp
Fixes #1159 by using the built-in TF2 ConVar ` tf_dropped_weapon_lifetime` and killing all **tf_dropped_weapon** entities when shavit_misc_noweapondrops is changed to 1.
The TF2_KillDroppedWeapons function is necessary because existing dropped weapons continue to live out their lifetime even after `tf_dropped_weapon_lifetime` is changed to 0.
> [TF2] Fix broken NoWeaponDrops (shavit-misc)

- addons/sourcemod/gamedata/shavit.games.txt
- addons/sourcemod/scripting/shavit-tas.sp
No tf2 because I hate that game.
The method used for csgo can be also used for css/tf2, but considering vtable are exposed so I chose to use [CGameMovement::CategorizePosition](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/gamemovement.cpp#L3774-L3780)
> Use signature for m_surfaceFriction instead of doing netprop±offset

- addons/sourcemod/scripting/shavit-hud.sp
> show timer in hud when started in start zone 

- addons/sourcemod/scripting/include/shavit/sql-create-tables-and-migrations.sp
Fixes #1175. I decided to go with `ON UPDATE RESTRICT ON DELETE RESTRICT` referential actions instead of the CASCADE actions used by the constraint in DBs created <= v3.0.8. RESTRICT would have stopped the REPLACE SQLite query from working/cascading to delete all of the user's playertimes. It does mean that all child playertimes have to be deleted before the user table row can be, but this is already how DeleteRestOfUser works so should be fine.
MySQL supports `ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY`. Unfortunately, [SQLite does not](https://stackoverflow.com/a/1884841), which means creating a temporary table to store existing playertimes data, dropping playertimes and re-creating playertimes with the correct FK constraint.
For SQLite I initially tried `PRAGMA …
>  Add migration to update or add auth FK constraint in playertimes

- addons/sourcemod/scripting/include/shavit/sql-create-tables-and-migrations.sp
[SQLite uses ROWID](https://sqlite.org/lang_createtable.html#rowid) to uniquely identify each row in a table, and a column with type INTEGER PRIMARY KEY becomes an alias for that ROWID value. The CREATE TABLE statement for mapzones since the beginning (1.1b) has been `id INT AUTO_INCREMENT`, but the column _has_ to be of INTEGER type for it to act as a ROWID alias (not INT). Because id is therefore acting as a ordinary integer table column, all id rows in mapzones have been NULL in SQLite DBs since the plugin was released.
This migration fixes that and gives each map zone a unique identifier for SQLite DBs.
> Add SQLite migration to fix mapzones having NULL id for all rows

- addons/sourcemod/scripting/shavit-zones.sp
TF2's bounding box is `48x48x82` compared to CS:S `32x32x62` and CS:GO `32x32x72`. As such, the default value of gCV_BoxOffset (bbox width / 2) is slightly off the player's center for TF2.
In SetZoneMinsMaxs, the `height` variable is half the bbox height but does not use the correct value for TF2 either (uses CS:S 62.0 instead of 82.0). This PR adds the correct bbox values for TF2.
As an aside, I did wonder if having `height` be constantly set to half the bbox height is really the desired behavior. E.g. if `shavit_zones_box_offset = 0`, why should distance_z be offset by half the bbox height yet have no offset for distance_x/y?
https://github.com/shavitush/bhoptimer/blob/a6da4358de06937b095dcafd79050e4ea937844a/addons/sourcemod/scripting/shavit-zones.sp#L5104-L5114
> [TF2] Add correct bounding box values for shavit_zones_box_offset

- addons/sourcemod/scripting/shavit-rankings.sp
The sqlite rankings support depends on https://github.com/alliedmodders/sourcemod/pull/1886
For Mysql >= 8.0 & Mariadb >= 10.2, GetWeightedPoints won't be needed anymore.
The queries should be double-checked
> Wip sqlite rankings support & GetWeightedPoints deprecation

- addons/sourcemod/scripting/shavit-misc.sp
Fixes DMG_CRUSH (by moving/falling objects for example (with cs_enable_player_physics_box 1))
Handles correctly damage dealt by point_hurt entities (see https://developer.valvesoftware.com/wiki/Point_hurt)
~~**IMPORTANT:** `shavit_misc_godmode 1` will now block damage dealt by ALL entities that aren't players, instead of only 0 (world).
If you don't want to make it like that, please tell me.~~
-- Added `shavit_misc_godmode 4` for that
> Godmode fix for DMG_CRUSH and point_hurt

- addons/sourcemod/configs/shavit-styles.cfg
it's historically always been 400
> use correct gravity for LG

- addons/sourcemod/scripting/shavit-mapchooser.sp
- addons/sourcemod/scripting/shavit-rankings.sp
`shavit-mapchooser` menus want tiers from `shavit-rankings`
`shavit-rankings` probably won't send tiers on the first map because it's waiting for the database handle which probably comes after `OnMapStart` which means it skips tier retrieval for the first map... which means `shavit-mapchooser` never makes the (enhanced?) nominate menu...
shitify `OnMapStart` in `shavit-rankings` and add more bools to fix...
This broke in https://github.com/shavitush/bhoptimer/pull/1182
> fixups for mapchooser nominate menu after sqlite support was added to shavit-rankings

- addons/sourcemod/scripting/shavit-replay-playback.sp
This allows editing the replay bot's name through the frame_cache_t of the replay data, which is useful for personal replays. Without this change, the replay bot's name after calling Shavit_StartReplayFromFrameCache would be the current WR's player name.
> Allow updating replay bot name without being a WR

- addons/sourcemod/scripting/shavit-zones.sp
This is a fix to the stage restart command I added a while ago for surf.
> Make stage restart command take player to beginning when in end zone

- .github/workflows/ci.yml
- README.md
- addons/sourcemod/gamedata/shavit.games.txt
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-tas.sp
Only works on 32-bit. DHooks needs more support for x64 before bhoptimer can work on it.
> (WIP) Gamedata post 2025-02-18 update

- addons/sourcemod/scripting/shavit-misc.sp
Add functionality to turn off noclip on timer restart, disabled by default u.u
I used to use a separate plugin I made for this, but figured it should be in the main plugin itself as a cvar instead. Since adding as a cvar, may as well see if it is wanted upstream.
> shavit-misc Add cvar UnNoclipOnRestart

- addons/sourcemod/configs/shavit-styles.cfg
- addons/sourcemod/scripting/include/shavit/style-settings.sp
- addons/sourcemod/scripting/shavit-core.sp
- addons/sourcemod/scripting/shavit-misc.sp
- addons/sourcemod/scripting/shavit-zones.sp
- addons/sourcemod/translations/shavit-zones.phrases.txt
This PR changes a few things:
- The startzone code in shavit-misc duplicates some functionality for certain zone types, and one of those duplicates doesn't call StyleMaxPrestrafe even though the rest of the code is identical.
- There is now a style configuration flag that overrides fLimit, so modes that use it can enforce a different speedcap than the ~290 that it normally does
- This style configuration can be overridden by the contents of the data field of the startzone. If the startzone has 400 and the config file has 350, it will use 400.
- There is now a new prespeed type (6) that behaves like type 5 but also blocks prehopping. One thing I noticed is that the code to block bhops in mode 2, 3, and 6 only triggers on the first tick that the player hit the ground. You can still scroll …
> Startzone speed limit flexibility

- addons/sourcemod/scripting/shavit-stats.sp
L 06/25/2025 - 15:22:48: [SM] Exception reported: Client 2 is not in game
L 06/25/2025 - 15:22:48: [SM] Blaming: shavit/shavit-stats.smx
L 06/25/2025 - 15:22:48: [SM] Call stack trace:
L 06/25/2025 - 15:22:48: [SM]   [0] IsPlayerAlive
L 06/25/2025 - 15:22:48: [SM]   [1] Line 439, shavit-stats.sp::SavePlaytime222
L 06/25/2025 - 15:22:48: [SM]   [2] Line 498, shavit-stats.sp::SavePlaytime
L 06/25/2025 - 15:22:48: [SM]   [3] Line 351, shavit-stats.sp::OnClientDisconnect
> shavit-stats.sp - fix error due to IsPlayerAlive() being called on disconnected client

- addons/sourcemod/scripting/shavit-replay-playback.sp
QoL change. no reason to keep the replay menu open when spawning. works very well with the menu persistence changes
> shavit-replay-playback.sp - close replay menu on spawn (if it's open)
